banka/urls.py
from django.urls import path, include
from django.views.generic import RedirectView
from . import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('banka_app/', include('banka_app.urls')),
    path('', RedirectView.as_view(url='banka_app/')),
]

admin.autodiscover()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

banka_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('uzivatele/', views.uzivatele, name='uzivatele'),
    path('uzivatele/<int:uzivatel_id>/', views.detail_uzivatele, name='detail-uzivatele'),
    path('pridat-uzivatele/', views.add_user, name='pridat-uzivatele'),
    path('podminky/', views.podminky, name='podminky'),
    path('', views.banka_aplikace, name='banka_aplikace'),
]

banka_app/models.py
from django.db import models
from django.utils import timezone

class Uzivatele(models.Model):
    jmeno = models.CharField(max_length=100, verbose_name='Jméno')
    prijmeni = models.CharField(max_length=100, verbose_name='Příjmení')
    email = models.EmailField(unique=True, verbose_name='E-mail')
    heslo = models.CharField(max_length=50)
    datum_vytvoreni = models.DateTimeField(auto_now_add=True)
    datum_posledniho_prihlaseni = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Uživatel banky'
        verbose_name_plural = 'Uživatelé banky'
        ordering = ['prijmeni']

    def __str__(self):
        return f"{self.prijmeni} {self.jmeno}"
    
class Ucty(models.Model):
    cislo_uctu = models.CharField(max_length=20, unique=True, verbose_name='Číslo účtu' )
    uzivatel = models.ForeignKey(Uzivatele, on_delete=models.CASCADE, verbose_name='Uživatel')
    zustatek = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Zůstatek na účtu' )
   
    class Meta:
        verbose_name = 'Účet'
        verbose_name_plural = 'Účty'
        ordering = ['uzivatel']

    def __str__(self):
        return self.cislo_uctu
    

class Prevody(models.Model):
    zdrojovy_ucet = models.ForeignKey(Ucty, on_delete=models.CASCADE, related_name='prevod_od')
    cilovy_ucet = models.ForeignKey(Ucty, on_delete=models.CASCADE, related_name='prevod_do')
    castka = models.DecimalField(max_digits=10, decimal_places=2)
    datum = models.DateTimeField(auto_now_add=True)
    typ_prevodu = models.CharField(max_length=100)
    
    class Meta:
        verbose_name = 'Převod'
        verbose_name_plural = 'Převody'
        ordering = ['datum']

    def __str__(self):
        return f"{self.typ_prevodu} ({self.datum})" 


banka_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Uzivatele, Ucty
from django.db.models import Max, Min

def uzivatele(request):
    posledni_uzivatel = Uzivatele.objects.latest('datum_vytvoreni')
    prvni_uzivatel = Uzivatele.objects.earliest('datum_vytvoreni')
    uzivatele = Uzivatele.objects.all()
    return render(request, 'accounts.html', {'uzivatele': uzivatele,'posledni_uzivatel': posledni_uzivatel, 'prvni_uzivatel': prvni_uzivatel})

def detail_uzivatele(request, uzivatel_id):
    uzivatel = get_object_or_404(Uzivatele, pk=uzivatel_id)
    ucty = Ucty.objects.filter(uzivatel=uzivatel) 
    return render(request, 'detail_account.html', {'uzivatel': uzivatel, 'ucty': ucty})

def add_user(request):
    if request.method == 'POST':
        jmeno = request.POST['jmeno']
        prijmeni = request.POST['prijmeni']
        email = request.POST['email']
        heslo = request.POST['heslo']
        Uzivatele.objects.create(jmeno=jmeno, prijmeni=prijmeni, email=email, heslo=heslo)
        return redirect('uzivatele')
    return render(request, 'add_user.html')

def podminky(request):
    return render(request, 'podminky.html')

def banka_aplikace(request):
    return render(request, 'banka_aplikace.html')

banka_app/templates/accounts.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Accounts - Bank App
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <div class="list">
                <div class="mt-3 p-5">
                    <h1>Seznam uživatelů</h1>
                </div>
                <table class="table table-striped mt-3">
                    <thead>
                        <tr>
                            <th>Jméno uživatele</th>
                            <th>Detail</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for uzivatel in uzivatele %}
                        <tr>
                            <td>{{ uzivatel.jmeno }} {{ uzivatel.prijmeni }}</td>
                            <td><a href="{% url 'detail-uzivatele' uzivatel.id %}"
                                    class="btn btn-outline-dark">Detail</a></td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="2">Žádní uživatelé nebyli nalezeni.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-4">
            <div class="list-side">
                <h2>Informace o uživatelích</h2>
                <ul>
                    <li>Počet uživatelů: <b>{{ uzivatele.count }}</b></li>
                    <li>Nejnovější uživatel: <b>{{ posledni_uzivatel.jmeno }} {{ posledni_uzivatel.prijmeni }}</b></li>
                    <li>První uživatel: <b>{{ prvni_uzivatel.jmeno }} {{ prvni_uzivatel.prijmeni }}</b></li>
                </ul>
                <a href="{% url 'pridat-uzivatele' %}" class="btn btn-warning">Přidat uživatele</a>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" href="{% static 'css/style-accounts.css' %}">
{% endblock %}

banka_app/templates/add_user.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Pridat uzivatele
{% endblock %}

{% block content %}
<div class="list">
  <h1>Přidat uživatele</h1>
  <form method="POST">
    {% csrf_token %}
    <div class="forma">
      <div class="zadavani">
        <label for="jmeno">Jméno:</label>
        <input type="text" class="vstup" name="jmeno" required><br>
      </div>
      <div class="zadavani">
        <label for="prijmeni">Příjmení:</label>
        <input type="text" class="vstup" name="prijmeni" required><br>
      </div>
      <div class="zadavani">
        <label for="email">Email:</label>
        <input type="email" class="vstup" name="email" required><br>
      </div>
      <div class="zadavani">
        <label for="heslo">Heslo:</label>
        <input type="password" class="vstup" name="heslo" required><br>
      </div>
      <div class="zadavani">
        <input name="selectedValue" class="souhlas" id="souhlas" type="checkbox" value="ANO" required> 
        <p>Souhlasím s <a href="{% url 'podminky' %}"><b>podmínkami</b></a></p>
      </div>
      <button type="submit" class="pridat">Přidat</button>
    </div>
  </form>
</div>
<link rel="stylesheet" href="{% static 'css/style-pridat-uzivatele.css' %}">
{% endblock %}

banka_app/templates/banka_aplikace.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Bank App
{% endblock %}

{% block content %}
<div class="p-5 bg-warning text-white ">
    <h1>BANKA 55XO7</h1>
</div>
<span style="font-size:30px;cursor:pointer " onclick="openNav()">&#9776; OPEN</span>
<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a href="{% url 'uzivatele' %}">Uživatelé</a>
    <a href="{% url 'pridat-uzivatele' %}">Přidat uživatele</a>
</div>
<div class="list">
    <div class="container mt-5">
        <div class="row">
            <div class="col-sm-4 pt-5">
                <h3>Bankovnictví</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
                <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
            </div>
            <div class="col-sm-4 pt-5">
                <h3>Účty</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
                <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
            </div>
            <div class="col-sm-4 pt-5">
                <h3>Přidání účtu</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
                <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" href="{% static 'css/style-banka-aplikace.css' %}">
<script src="{% static 'js/script-banka-aplikace.js' %}"></script>
{% endblock %}

banka_app/templates/base.html
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

banka_app/templates/detail_account.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Detail uživatele - Bank App
{% endblock %}

{% block content %}
<div class="detail">
    <h1>Detail uživatele</h1>
    {% if uzivatel %}
    <div class="detail-info">
        <p><strong>Jméno: </strong> {{ uzivatel.jmeno }}</p>
        <p><strong>Příjmení: </strong> {{ uzivatel.prijmeni }}</p>
        <p><strong>Email: </strong> {{ uzivatel.email }}</p>
        <p><strong>Datum vytvoření: </strong> {{ uzivatel.datum_vytvoreni }}</p>
        <p><strong>Datum posledního přihlášení: </strong> {{ uzivatel.datum_posledniho_prihlaseni }}</p>
        <h2>Účet:</h2>
        {% for ucet in uzivatel.ucty_set.all %}
        <p><strong>Číslo účtu: </strong> {{ ucet.cislo_uctu }}</p>
        <p><strong>Zůstatek na účtu: </strong> {{ ucet.zustatek }} Kč </p>
        {% empty %}
        <p>Tento uživatel nemá žádné účty.</p>
        {% endfor %}
    </div>
    {% else %}
    <div class="nenalezen">
        <p>Uživatel nebyl nalezen.</p>
    </div>
    {% endif %}
    <a href="{% url 'uzivatele' %}"><button class="pridat">Zpět na seznam uživatelů</button></a>
</div>


<link rel="stylesheet" href="{% static 'css/style-detail.css' %}">
{% endblock %}

banka_app/templates/podminky.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Podmínky
{% endblock %}

{% block content %}
<div class="list">
    <h1>Podmínky</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="forma">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam autem minus
                nisi voluptatum doloribus alias rerum veniam, facilis, nihil non tempore numquam,
                eveniet maiores corporis nesciunt rem. Quibusdam porro at, quisquam optio placeat
                ex ipsam tenetur quasi cum. Ipsa eos enim ipsam labore fuga mollitia omnis dolorem
                in ut facere.
            <br>
            <br>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam autem minus
                nisi voluptatum doloribus alias rerum veniam, facilis, nihil non tempore numquam,
                eveniet maiores corporis nesciunt rem. Quibusdam porro at, quisquam optio placeat
                ex ipsam tenetur quasi cum. Ipsa eos enim ipsam labore fuga mollitia omnis dolorem
                in ut facere.
            <br>
            <br>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam autem minus
                nisi voluptatum doloribus alias rerum veniam, facilis, nihil non tempore numquam,
                eveniet maiores corporis nesciunt rem. Quibusdam porro at, quisquam optio placeat
                ex ipsam tenetur quasi cum. Ipsa eos enim ipsam labore fuga mollitia omnis dolorem
                in ut facere.
            </p>
            <br>
            <br>
            <button class="pridat"><a href="{% url 'pridat-uzivatele' %}">Zpět na přidání účtu</a></button>
        </div>
    </form>
</div>
<link rel="stylesheet" href="{% static 'css/style-pridat-uzivatele.css' %}">
{% endblock %}